#!/bin/bash

# Forma de uso:
#
#         perfctr <CORE_ID> <GRUPO_PERFORMANCE> ./matmult <opcoe_matmult>
#
# Exemplo, para fazer as medições de performance de FLOPS_DP no core 3
#
#         perfctr 3 FLOPS_DP ./matmult 64
#

#VALORES_TESTE=(64 100 128 200 256 512 600 900 1024 2000 2048 3000 4000);
VALORES_TESTE=(64 100 128 200)
METRICAS=("L3" "L2CACHE" "ENERGY" "FLOPS_DP")

LIKWID_CMD="likwid-perfctr -C $1 -g $2 -m"
shift 2

echo "performance" > /sys/devices/system/cpu/cpufreq/policy${1}/scaling_governor

#make purge matmult
for k in ${METRICAS[@]}
do
        > $k.log
        for n in ${VALORES_TESTE[@]}
        do
                likwid-perfctr -C 3 -g $k -m ./matmult $n >> $k.log
        done
done

grep "L3 bandwidth" L3.log > L3.dat
grep "L2 miss ratio" L2CACHE.log > L2CACHE.dat
grep "Energy \[J\]" ENERGY.log > ENERGY.dat
grep "  DP MFLOP\/s" FLOPS_DP.log > FLOPS_DP.dat

#${LIKWID_CMD} $*

echo "powersave" > /sys/devices/system/cpu/cpufreq/policy${1}/scaling_governor

# Para obter topologia dos cpu's
#      likwid-topology -c -g

# Para obter lista de grupos de indicadores de performance:
#      likwid-perfctr -a

# Para obter lista de Eventos e Contadores
#      likwid-perfctr -e

