#!/bin/bash

# Forma de uso:
#
#         perfctr <CORE_ID> <GRUPO_PERFORMANCE> ./matmult <opcoe_matmult>
#
# Exemplo, para fazer as medições de performance de FLOPS_DP no core 3
#
#         perfctr 3 FLOPS_DP ./matmult 64
#

VALORES_TESTE=(64 100 128 200 256 512 600 900 1024 2000 2048 3000 4000);
#VALORES_TESTE=(64 100 128 200 256 512 600 900 1024 2000 2048)
METRICAS=("L3" "L2CACHE" "ENERGY" "FLOPS_DP")

LIKWID_CMD="likwid-perfctr -C $1 -g $2 -m"
shift 2

echo "performance" > /sys/devices/system/cpu/cpufreq/policy3/scaling_governor

#make purge matmult
for k in ${METRICAS[@]}
do
        > ./log/$k.log
        for n in ${VALORES_TESTE[@]}
        do
                likwid-perfctr -C 3 -g $k -m ./matmult $n >> ./log/$k.log
        done
done

grep "L3 bandwidth" ./log/L3.log > ./dat/L3.dat
grep "L2 miss ratio" ./log/L2CACHE.log > ./dat/L2CACHE.dat
grep "Energy \[J\]" ./log/ENERGY.log > ./dat/ENERGY.dat
grep "  DP MFLOP\/s" ./log/FLOPS_DP.log > ./dat/FLOPS_DP.dat

echo "powersave" > /sys/devices/system/cpu/cpufreq/policy3/scaling_governor
