#!/bin/bash

METRICAS=("L3" "L2CACHE" "ENERGY" "FLOPS_DP")

grep "L3 bandwidth" ./log/L3.log > ./dat/L3.dat
grep "L2 miss ratio" ./log/L2CACHE.log > ./dat/L2CACHE.dat
grep "Energy \[J\]" ./log/ENERGY.log > ./dat/ENERGY.dat
grep "  DP MFLOP\/s" ./log/FLOPS_DP.log > ./dat/FLOPS_DP.dat

for k in ${METRICAS[@]}
do
        grep "Tempo" ./log/$k.log > ./dat/TEMPO_$k.dat
done

