#!/bin/bash

#VALORES_TESTE=(64 128 200 256 512 600 800 1024 2000 3000 4096 6000 7000 10000 50000)
VALORES_TESTE=(64 128 200 256 512 600 800 1024)
METRICAS=("L3" "L2CACHE" "ENERGY" "FLOPS_DP")

#shift 2

echo "performance" > /sys/devices/system/cpu/cpufreq/policy3/scaling_governor

for k in ${METRICAS[@]}
do
        > log/$k.log
        for n in ${VALORES_TESTE[@]}
        do
                likwid-perfctr -C 3 -g $k -m ./ajustePol < testes/$n.in  >> log/$k.log
        done
done

#grep "L3 bandwidth" ./log/L3.log > ./dat/L3.dat
#grep "L2 miss ratio" ./log/L2CACHE.log > ./dat/L2CACHE.dat
#grep "Energy \[J\]" ./log/ENERGY.log > ./dat/ENERGY.dat
#grep "DP MFLOP\/s" ./log/FLOPS_DP.log > ./dat/FLOPS_DP.dat
#
#for k in ${METRICAS[@]}
#do
#        grep "Tempo" ./log/$k.log > ./dat/TEMPO_$k.dat
#done
#
echo "powersave" > /sys/devices/system/cpu/cpufreq/policy3/scaling_governor
